# Generated by Django 6.1.1 on 2026-09-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0003_tipoinmueble_alter_inmueble_tipo_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
