# Generated by Django 6.1.1 on 2026-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario_por_defecto',
            field=models.CharField(choices=[('arrendador', 'arrendador'), ('arrendatario', 'arrendatario')], verbose_name='Tipo_Usuario'),
        ),
    ]
