# Generated by Django 6.1 on 2026-08-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('contact_form_uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField()),
                ('message', models.TextField()),
            ],
        ),
    ]
