# Generated by Django 6.1 on 2026-08-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='customer_name',
            field=models.CharField(max_length=64),
        ),
    ]
