# Generated by Django 6.1.1 on 2026-09-21 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_inmueble_fecha_creacion_inmueble_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
